[package]
name = "salvo_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
salvo = "0.74.3"
tokio = { version = "1.42.0", features = ["macros"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
